add .aicoe-ci.yaml
thoth-station/invectio pull request #97
Opened 2020-11-30 20:25 UTC by bissenbay

Fixes: https://github.com/thoth-station/invectio/issues/96

2020-11-30 20:25 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvectio).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/invectio/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2020-11-30 20:26 UTC, bissenbay commented
@fridex @harshad16 I would like you to pay closer attention to the added `.aicoe-ci.yaml` file because I just copy/pasted from `adviser` and I don't see `invectio` directory in https://github.com/thoth-station/thoth-application, so, to be honest, I'm not quiet sure whether we need add it or not?

2020-12-01 06:37 UTC, harshad16 requested changes
Thanks for the changes, suggested the changes 
please have a look

2020-12-01 06:37 UTC, harshad16 commented on .aicoe-ci.yaml
> +  overlay-contextpath: "invectio/overlays/test/imagestreamtag.yaml"
This is not needed as invectio is a python package module, not a application component.

2020-12-01 06:37 UTC, harshad16 commented on .aicoe-ci.yaml
> +build:
Add the following code snippet instead of the build: 
```
release:
  - upload-pypi-sesheta
```

2020-12-01 06:37 UTC, harshad16 commented on .aicoe-ci.yaml
> +  - thoth-build
remove this check as well.

2020-12-01 14:11 UTC, bissenbay commented
thanks @harshad16 , PTAL https://github.com/thoth-station/invectio/pull/97/commits/11cc16770ae5b8d0dd03d1beabbe96839b29addf

2020-12-03 14:11 UTC, bissenbay commented
@fridex @harshad16 PTAL

2020-12-03 14:54 UTC, harshad16 approved these changes
thanks :100:

2020-12-03 14:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/invectio/pull/97#pullrequestreview-544035538" title="Approved">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvectio).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/invectio/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2020-12-03 14:56 UTC, bissenbay commented
/assign @fridex

2020-12-03 19:41 UTC, fridex approved these changes
:100:

2020-12-03 19:41 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/invectio/pull/97#pullrequestreview-544327792" title="Approved">fridex</a>*, *<a href="https://github.com/thoth-station/invectio/pull/97#pullrequestreview-544035538" title="Approved">harshad16</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvectio).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/invectio/blob/master/OWNERS)~~ [fridex]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-03 19:43 UTC, merged